baseURL = 'https://philliams.github.io/'
languageCode = 'en-us'
title = 'An Hour A Day'
theme = 'PaperMod'

# navbar config
[menu]
[[menu.main]]
    name = 'Publications'
    pageRef = 'publications.md'
    weight = 10
[[menu.main]]
    name = 'About Me'
    pageRef = 'about.md'
    weight = 20
[[menu.main]]
    name = 'Posts'
    pageRef = '/posts/'
    weight = 30
[[menu.main]]
    name = 'Search'
    pageRef = 'search.md'
    weight = 40
[[menu.main]]
    name = 'Tags'
    pageRef = '/tags/'
    weight = 50

# used to enable iframes for graphs
[markup.goldmark.renderer]
    unsafe= true

# configure outputs for search page
[outputs]
    home = ['HTML', 'RSS', 'JSON']

# configure homepage layout
[params.homeInfoParams]
Title = "Hi there wave"
Content = "Can be Info, links, about..."

[[params.socialIcons]]
name = "<platform>"
url = "<link>"

[[params.socialIcons]]
name = "<platform 2>"
url = "<link2>"

