name: Blog-CI

# run CI anytime there is a push to main branch or trigger manually
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  
jobs:
  build:
    # use ubuntu-22.04 because it has docker pre-installed
    # see : https://github.com/actions/runner-images
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    # run one instance per workflow per branch
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    # CI steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Build image for hugo build
        run: make build_docker_build
      - name: Build blog
        run: make build
      - name: Remove docs .gitignore
        run: rm ./blog_build/.gitignore
      - name: Deploy documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog_build/
          force_orphan: true